name: Build Web App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server
        npm install 
        
    - name: Prepare and Run Local Database 
      run: |
        cd server
        docker build -t kupi_i_vozi_database .
        docker run -dp 5432:5432 kupi_i_vozi_database
        
    - name: Run server
      run: npm run start
      
  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd client
        npm install 

    - name: Run client
      run: npm run start
